function [layers, options, winSize, rnnDesc] = rnndef21
	layers = [
		sequenceInputLayer(8, 'Normalization', 'zscore')
		lstmLayer(65, 'OutputMode', 'last')
		fullyConnectedLayer(1)
		regressionLayer
	];
	options = trainingOptions('sgdm', ...
		'MiniBatchSize', 300, ...
		'InitialLearnRate', 0.01, ...
		'Momentum', 0.9, ...
		'GradientThreshold', 1, ...
		'Shuffle', 'every-epoch', ...
		'SequencePaddingDirection', 'left' ...
	);
	winSize = 10;
	rnnDesc = "Training algorithm: sgdm";
end
