layers = [
	sequenceInputLayer(8, 'Normalization', 'zscore')
	lstmLayer(65, 'OutputMode', 'last')
	fullyConnectedLayer(1)
	regressionLayer
];
options = trainingOptions('rmsprop', ...
	'Shuffle', 'every-epoch', ...
	'InitialLearnRate', 0.1, ...
	'LearnRateSchedule', 'piecewise', ...
	'LearnRateDropFactor', 0.4, ...
	'LearnRateDropPeriod', 50, ...
	'L2Regularization', 0.0001, ...
	'MiniBatchSize', 300, ...
	'ValidationFrequency', 20, ...
	'ValidationPatience', 350, ...
	'OutputNetwork', 'best-validation-loss', ...
	'SequencePaddingDirection', 'left', ...
	'SquaredGradientDecayFactor', 0.9, ...
	'Epsilon', 1e-8 ...
);
winSize = 10;
